# Generated by Django 5.0.6 on 2024-05-16 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StreamingContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=50)),
                ('cast', models.JSONField(blank=True, default=list)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('date_added', models.CharField(max_length=50)),
                ('release_year', models.IntegerField()),
                ('rating', models.CharField(max_length=10)),
                ('duration', models.CharField(max_length=50)),
                ('listed_in', models.JSONField(blank=True, default=list)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
    ]
